name: buntsmatrimony
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: "none"


version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.1
  provider: ^6.0.5
  in_app_purchase: ^3.2.1
  dropdown_button2: ^2.3.9
  # image_picker: ^1.1.2
  crypto: ^3.0.3
  image_cropper: ^9.0.0
  image_picker: ^0.8.5+3
  dio: ^5.0.0
  fluttertoast: ^8.0.9
  mime: ^1.0.4
  dropdown_search: ^5.0.6
  multi_select_flutter: ^4.1.3
  url_launcher: ^6.1.14
  flutter_cashfree_pg_sdk: ^2.2.5+43
  rflutter_alert: ^2.0.4
  jwt_decode: ^0.3.1
  jwt_decoder: ^2.0.1
  smooth_page_indicator: ^1.2.1
 

  # Cupertino icons for iOS-style icons
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  connectivity_plus: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for good coding practices
  http: ^1.3.0
  flutter_lints: ^5.0.0

flutter:
  # Ensures material icons are available
  uses-material-design: true

  # Adding assets
  assets:
    - assets/1.png
    - assets/2.png
    - assets/default_avatar.png
    - assets/EditAdditional.jpg
    - assets/EditEducation.jpg
    - assets/EditFamily.jpg
    - assets/EditPhoto.jpg
    - assets/fillyourprofile.jpg
    - assets/horoscope.jpg
    - assets/Welcome.jpg
    - assets/verification.png
    - assets/verification_new.png
    - assets/icon-144x144.png
    - assets/buntslogo.jpg
    
